import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Overlay_Context from "@/context/overlay_context"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Overlay_Context value={false}>
        <Navbar/>
        {children}
        </Overlay_Context>
      </body>
    </html>
  );
}
