import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Overlay from "@/components/Overlay";
import {Overlaysetting} from "@/context/overlay_context"
import {Decksetting} from "@/context/deck_context"

// TODO: Cache Components adoption. Refactor this route so this opt-out can be removed.
// See: https://nextjs.org/docs/app/guides/migrating-to-cache-components
export const instant = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Overlaysetting>
        <Decksetting>
          <Overlay/>
          <Navbar/>
          {children}
        </Decksetting>
        </Overlaysetting>
      </body>
    </html>
  );
}
