import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Overlay from "@/components/Overlay";
import {Overlaysetting} from "@/context/overlay_context"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Overlaysetting>
          <Overlay/>
          <Navbar/>
          {children}
        </Overlaysetting>
      </body>
    </html>
  );
}
